-- TBL_MEMBER 테이블 생성
CREATE TABLE C##BJH.TBL_MEMBER
(
   MEMBER_CD         NUMBER(5)     PRIMARY KEY
 , MEMBER_ID         VARCHAR2(30)  UNIQUE NOT NULL 
 , MEMBER_PW         VARCHAR2(30)  NOT NULL
 , MEMBER_NM         VARCHAR2(30)  NOT NULL
 , MEMBER_BIRTHDATE  DATE          NOT NULL
 , MEMBER_PHONE      VARCHAR2(11)  UNIQUE NOT NULL
 , MEMBER_STATUS     CHAR(1)       DEFAULT 'A' NOT NULL
 , MEMBER_REGDATE    DATE          DEFAULT SYSDATE
);

TABLESPACE TS_MAILME_BASE;

COMMENT ON TABLE C##BJH.TBL_MEMBER IS '회원';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_CD IS        '회원 번호';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_ID IS        '회원 아이디';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_PW IS        '회원 비밀번호';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_NM IS        '회원 이름';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_BIRTHDATE IS '회원 생년월일';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_PHONE IS     '회원 핸드폰번호';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_STATUS IS   '회원 활동 상태';
COMMENT ON COLUMN C##BJH.TBL_MEMBER.MEMBER_REGDATE IS   '회원 가입일';

-- MEMBER_CD 시퀀스 생성
CREATE SEQUENCE SEQ_TBL_MEMBER_MEMBER_CD nocache;

COMMIT;

-- TBL_MAIL 테이블 생성
CREATE TABLE C##BJH.TBL_MAIL
(
    MAIL_CD          NUMBER(5)     PRIMARY KEY,
    MAIL_TITLE       VARCHAR2(100) NOT NULL,
    MAIL_CONTENT     VARCHAR2(4000) NOT NULL,
    MAIL_SENDER_CD   NUMBER(5) NOT NULL,
    MAIL_RECEIVER_CD NUMBER(5) NOT NULL,
    MAIL_OPEN_CHK    NUMBER(1) DEFAULT 0,
    MAIL_SENT_DATE   DATE DEFAULT SYSDATE
);

COMMIT;

TABLESPACE TS_MAILME_BASE;

COMMENT ON TABLE C##BJH.TBL_MAIL IS '메일';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_CD IS           '메일 번호';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_TITLE IS        '메일 제목';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_CONTENT IS      '메일 내용';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_SENDER_CD IS    '메일 송신자';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_RECEIVER_CD IS  '메일 수신자';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_OPEN_CHK IS     '메일 수신 여부';
COMMENT ON COLUMN C##BJH.TBL_MAIL.MAIL_SENT_DATE IS    '메일 송신일';

-- MAIL_CD용 시퀀스 생성
CREATE SEQUENCE SEQ_TBL_MAIL_MAIL_CD nocache;
COMMIT;

-- TBL_TRASH 테이블 생성
CREATE TABLE C##BJH.TBL_TRASH
(
   TRASH_CD   NUMBER(5)  PRIMARY KEY
 , MAIL_CD    NUMBER(5)  NOT NULL
 , MEMBER_CD  NUMBER(5)  NOT NULL
 , PERMANENT  NUMBER(1)  DEFAULT 0
 , DEL_DATE   DATE       DEFAULT SYSDATE
);

TABLESPACE TS_MAILME_BASE;

-- TRASH_CD용 시퀀스 생성
CREATE SEQUENCE SEQ_TBL_TRASH_TRASH_CD nocache;
COMMIT;

COMMENT ON TABLE C##BJH.TBL_TRASH IS '휴지통';
COMMENT ON COLUMN C##BJH.TBL_TRASH.TRASH_CD  IS '휴지통 번호';
COMMENT ON COLUMN C##BJH.TBL_TRASH.MAIL_CD   IS '메일 번호';
COMMENT ON COLUMN C##BJH.TBL_TRASH.MEMBER_CD IS '삭제 멤버 번호';
COMMENT ON COLUMN C##BJH.TBL_TRASH.PERMANENT IS '영구 삭제 여부';
COMMENT ON COLUMN C##BJH.TBL_TRASH.DEL_DATE  IS '삭제일';

COMMIT;

-- TBL_SPAM 테이블 생성
CREATE TABLE C##BJH.TBL_SPAM
(
   SPAM_CD       NUMBER(5)    PRIMARY KEY
 , SPAM_WORD     VARCHAR2(30) NOT NULL
 , MEMBER_CD     NUMBER(5)    NOT NULL
 , SPAM_REGDATE  DATE         DEFAULT SYSDATE 
 , CONSTRAINT FK_SPAM_MEMBER_CD FOREIGN KEY (MEMBER_CD)
   REFERENCES C##BJH.TBL_MEMBER (MEMBER_CD) ON DELETE CASCADE
);

TABLESPACE TS_MAILME_BASE;

COMMIT;
COMMENT ON TABLE C##BJH.TBL_SPAM IS '스팸';
COMMENT ON COLUMN C##BJH.TBL_SPAM.SPAM_CD  IS '스팸 번호';
COMMENT ON COLUMN C##BJH.TBL_SPAM.SPAM_WORD   IS '스팸 설정어';
COMMENT ON COLUMN C##BJH.TBL_SPAM.MEMBER_CD  IS '스팸 등록 멤버 번호';
COMMENT ON COLUMN C##BJH.TBL_SPAM.SPAM_REGDATE IS '스팸어 등록일';

-- SPAM_CD용 시퀀스 생성
CREATE SEQUENCE SEQ_TBL_SPAM_SPAM_CD nocache;
COMMIT;